= MfNF-Diagnostic-Scripts

Scripts to aggregate information on the articles of the
https://de.wikibooks.org/wiki/Mathe_f%C3%BCr_Nicht-Freaks[Mathe für
Nicht-Freaks] project.

== Scripts
Currently there are the following diagnostic scripts:

* *bad_finder.py*: Find broken links and ankers on the Mathe für Nicht-Freaks
   project.
* *boxen_finder.py*: Analyse the usage of te custom templates on the Mathe für
   Nicht-Freaks project.
* *double_usage_finder.py*: Analyse the double use of contents on the Mathe
   für Nicht-Freaks project.
* *gallery_finder.py*: Analyse the usage of galleries on the Mathe für
   Nicht-Freaks project.
* *ref_finder.py*: Analyse the usage of references on the Mathe für
   Nicht-Freaks project.
* *tex_macro_finder.py*: Collect a list of all TeX-macros used in math
  environments on the Mathe für Nicht-Freaks project.

If you can't be bothered to read the documentation (see below), you can just
run the script with python3. That is run

[source,bash]
python3 <script_name>

They have decent defaults. But if you want to use caching or comfortably store
information elsewhere, you should take a brief look at the documentation.

== Where can I get more information on the scripts?
Check the folder `doc`. You will find manpages for the individual scripts
there.

== I want to contribute something
Awesome! If you have something to contribute (e.g. a bug, an idea, a
diagnostic script, etc.), just create an
https://github.com/gruenerBogen/MfNF-Diagnostic-Scripts/issues[issue] or a
https://github.com/gruenerBogen/MfNF-Diagnostic-Scripts/pulls[pull
request]. Ideally, take a look at link:CONTRIBUTING.adoc[CONTRIBUTING] before
doing so.
